### ISSUE TITLE
Inconsistent Behavior with simple_form_tailwind.rb Changes

### ISSUE THREAD

**Issue by Sarkraf** [tarellel/simple_form-tailwind#10]
## Description
When using simple_form-tailwind, changes to the simple_form_tailwind.rb file behave inconsistently. Sometimes they're applied, and other times they’re ignored, creating unpredictable behavior.

## Solution
Adding the following line to the content array in tailwind.config.js fixes the issue:
`"./config/initializers/*.rb",`

<details>
<summary>Updated content example:</summary>

```js
  content: [
    "./public/*.html",
    "./app/helpers/**/*.rb",
    "./app/javascript/**/*.js",
    "./app/views/**/*.{erb,haml,html,slim}",
    "./config/initializers/*.rb", // Fix for this issue
  ],

```

</details>

## Suggestion

Include this path in the default configuration or document this requirement to prevent similar issues.

Let me know if you need more details!

**Comment by tarellel** [comment]
Good catch,
Thank you, I'll update the README with this applied.

**Comment by Sarkraf** [comment]
If you want, I'm currently modifying the gem to automate this. I can create a PR as soon as it's done. 😉
