### ISSUE TITLE
Not compiling erros class

### ISSUE THREAD

**Issue by oporpino** [tarellel/simple_form-tailwind#6]
When shows the error message, even with tag into the input, the tailwind does not compiling previous.

**Comment by tarellel** [comment]
Do you have a little more info I can go off of?

What error are you getting or not receiving? Is this something more to do with your simple_form config rather then the tailwind config in general?

**Comment by oporpino** [comment]
Im not receving an error, just the style is not applied. 

i have to put this `span class: "fix-tailwind text-rose-500 border-rose-500 hidden" #fix for tailwind compilation for simple_form` on the body to make work. I need to force all class that I am using and add hidden to don't show this span tag.
